name: Compile and Package Python Code

on:
  push:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10.0', '3.10.8', '3.10.12']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Compile Python files
      run: python -m compileall -b .

    - name: Remove unwanted files and directories
      run: |
        rm -rf .git/
        rm -rf .idea/
        rm .gitignore LICENSE package.json package-lock.json tailwind.config.js tailwind.sh

    - name: Create a zip package
      run: zip -r package.zip .

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: compiled-package-${{ matrix.python-version }}
        path: package.zip
